/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import arbol_main.arbol;
import generarNumero_main.GenerarNumero;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HP
 */
public class menu_frm extends javax.swing.JFrame {
    
    
    arbol arbol = new arbol();
    GenerarNumero recorridos = new GenerarNumero();
    /**
     * Creates new form menu_frm
     */
    public menu_frm() throws IOException {
        initComponents();
        arbol = recorridos.Generar();
        System.out.println("Numeros Generados");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_inorden = new javax.swing.JButton();
        btn_posorden = new javax.swing.JButton();
        btn_preorden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_inorden.setText("Generar Inorden");
        btn_inorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inordenActionPerformed(evt);
            }
        });

        btn_posorden.setText("Generar PosOrden");
        btn_posorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_posordenActionPerformed(evt);
            }
        });

        btn_preorden.setText("Generar PreOrden");
        btn_preorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_preordenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_inorden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_posorden, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(btn_preorden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(btn_inorden)
                .addGap(37, 37, 37)
                .addComponent(btn_posorden)
                .addGap(40, 40, 40)
                .addComponent(btn_preorden)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inordenActionPerformed
      try {
            // TODO add your handling code here:
            arbol.InOrden();
            System.out.println("InOrden generado correctamente");
            System.out.println("InOrden generado correctamente");
        } catch (IOException ex) {
            Logger.getLogger(menu_frm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_inordenActionPerformed

    private void btn_preordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_preordenActionPerformed
         try {
            // TODO add your handling code here:
            arbol.PreOrden(arbol.inicial);
            System.out.println("PreOrden Generado Correctamente");
            System.out.println("PreOrden Generado Correctamente");
        } catch (IOException ex) {
            Logger.getLogger(menu_frm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_preordenActionPerformed

    private void btn_posordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_posordenActionPerformed
            try {
            
            arbol.PosOrden();
            System.out.println("PosOrden Generado Correctamente");
            System.out.println("PosOrden Generado Correctamente");
        } catch (IOException ex) {
            Logger.getLogger(menu_frm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_posordenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new menu_frm().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(menu_frm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inorden;
    private javax.swing.JButton btn_posorden;
    private javax.swing.JButton btn_preorden;
    // End of variables declaration//GEN-END:variables
}
